AWSTemplateFormatVersion: '2010-09-09'
Description: 'Patient Vital Signs Monitoring - CloudTrail for Audit Logging'

Parameters:
  ProjectName:
    Type: String
    Default: VitalSignsMonitoring
    Description: Name of the project, used as prefix for resource names

Resources:
  # S3 Bucket for CloudTrail logs
  CloudTrailLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-cloudtrail-logs-${AWS::AccountId}-${AWS::Region}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 90  # Keep logs for 90 days to manage costs
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: Security
        - Key: Purpose
          Value: AuditLogging

  # CloudTrail Bucket Policy
  CloudTrailLogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudTrailLogsBucket
      PolicyDocument:
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt CloudTrailLogsBucket.Arn
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub '${CloudTrailLogsBucket.Arn}/*'
            Condition:
              StringEquals:
                's3:x-amz-acl': bucket-owner-full-control

  # CloudTrail for audit logging
  HealthcareCloudTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn: CloudTrailLogsBucketPolicy
    Properties:
      TrailName: !Sub '${ProjectName}-audit-trail'
      S3BucketName: !Ref CloudTrailLogsBucket
      S3KeyPrefix: 'healthcare-audit-logs'
      IncludeGlobalServiceEvents: true
      IsLogging: true
      IsMultiRegionTrail: false  # Single region to reduce costs
      EnableLogFileValidation: true
      EventSelectors:
        - ReadWriteType: All
          IncludeManagementEvents: true
          DataResources:
            - Type: 'AWS::DynamoDB::Table'
              Values: ['*']
            - Type: 'AWS::S3::Object'
              Values: ['*']
            - Type: 'AWS::Lambda::Function'
              Values: ['*']
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: Security
        - Key: Purpose
          Value: ComplianceAuditing

Outputs:
  CloudTrailArn:
    Description: ARN of the CloudTrail for healthcare audit logging
    Value: !GetAtt HealthcareCloudTrail.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CloudTrailArn'

  CloudTrailLogsBucket:
    Description: S3 bucket storing CloudTrail audit logs
    Value: !Ref CloudTrailLogsBucket
    Export:
      Name: !Sub '${AWS::StackName}-CloudTrailLogsBucket'