AWSTemplateFormatVersion: '2010-09-09'
Description: 'Patient Vital Signs Monitoring - S3 Resources with Academy Lab-Compatible Disaster Recovery'

Parameters:
  ProjectName:
    Type: String
    Default: VitalSignsMonitoring
    Description: Name of the project, used as prefix for resource names

Resources:
  # S3 Bucket for hosting the healthcare dashboard
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-dashboard-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - ETag
            Id: myCORSRuleId1
            MaxAge: 3600
      # 🚀 ENHANCED: Add versioning for disaster recovery
      VersioningConfiguration:
        Status: Enabled
      # 🚀 ENHANCED: Lifecycle management for cost optimization
      LifecycleConfiguration:
        Rules:
          - Id: WebsiteBackupRetention
            Status: Enabled
            NoncurrentVersionExpirationInDays: 7  # Keep old versions for 1 week
            NoncurrentVersionTransitions:
              - TransitionInDays: 1
                StorageClass: STANDARD_IA
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: Frontend
        - Key: DisasterRecovery
          Value: Versioning

  # Bucket policy to allow public read access for website hosting
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${WebsiteBucket.Arn}/*'

  # 🚀 ENHANCED: Primary patient data bucket with simplified DR features
  PatientDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-patient-data-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true  # Cost optimization
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      # 🚀 ENHANCED: Versioning for point-in-time recovery
      VersioningConfiguration:
        Status: Enabled
      # 🚀 ENHANCED: Multi-class storage and retention for DR
      LifecycleConfiguration:
        Rules:
          - Id: PatientDataDRStrategy
            Status: Enabled
            # Keep current versions in Standard for immediate access
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
              - TransitionInDays: 365
                StorageClass: DEEP_ARCHIVE
            # Keep old versions for disaster recovery
            NoncurrentVersionTransitions:
              - TransitionInDays: 1
                StorageClass: STANDARD_IA  # Immediate DR access
              - TransitionInDays: 30
                StorageClass: GLACIER     # Long-term DR backup
            NoncurrentVersionExpirationInDays: 2555  # 7 years retention (HIPAA compliance)
          - Id: IncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: PatientData
        - Key: Encryption
          Value: AES256
        - Key: DisasterRecovery
          Value: MultiTier
        - Key: Compliance
          Value: HIPAA
        - Key: RetentionYears
          Value: '7'

  # 🚀 NEW: Secondary backup bucket (same region, different AZ)
  PatientDataBackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-patient-backup-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: BackupRetention
            Status: Enabled
            Transitions:
              - TransitionInDays: 1
                StorageClass: STANDARD_IA  # Immediate cost savings
              - TransitionInDays: 30
                StorageClass: GLACIER
            NoncurrentVersionExpirationInDays: 90
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: DisasterRecoveryBackup
        - Key: Purpose
          Value: SecondaryBackup

  # 🚀 NEW: Archive bucket for long-term compliance storage
  PatientDataArchiveBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-patient-archive-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ArchiveImmediately
            Status: Enabled
            Transitions:
              - TransitionInDays: 0
                StorageClass: GLACIER  # Immediate archival
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: LongTermArchive
        - Key: Compliance
          Value: HIPAA-7Year
        - Key: StorageClass
          Value: Glacier

Outputs:
  WebsiteBucketName:
    Description: Name of the S3 bucket hosting the healthcare dashboard
    Value: !Ref WebsiteBucket
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteBucketName'

  WebsiteBucketArn:
    Description: ARN of the website bucket
    Value: !GetAtt WebsiteBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteBucketArn'

  WebsiteURL:
    Description: URL of the healthcare dashboard
    Value: !Sub 'http://${WebsiteBucket}.s3-website-${AWS::Region}.amazonaws.com'
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteURL'

  PatientDataBucket:
    Description: Name of the encrypted patient data bucket
    Value: !Ref PatientDataBucket
    Export:
      Name: !Sub '${AWS::StackName}-PatientDataBucket'

  PatientDataBucketArn:
    Description: ARN of the patient data bucket
    Value: !GetAtt PatientDataBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-PatientDataBucketArn'

  # 🚀 NEW: Disaster Recovery Outputs
  PatientDataBackupBucket:
    Description: Name of the secondary backup bucket
    Value: !Ref PatientDataBackupBucket
    Export:
      Name: !Sub '${AWS::StackName}-PatientDataBackupBucket'

  PatientDataArchiveBucket:
    Description: Name of the long-term archive bucket
    Value: !Ref PatientDataArchiveBucket
    Export:
      Name: !Sub '${AWS::StackName}-PatientDataArchiveBucket'

  DisasterRecoveryStrategy:
    Description: Multi-tiered disaster recovery approach
    Value: 'Versioning + Multi-bucket + Lifecycle transitions'
    Export:
      Name: !Sub '${AWS::StackName}-DRStrategy'

  DataRetentionPolicy:
    Description: Data retention and recovery capabilities
    Value: '7-year retention, Point-in-time recovery via versioning, Multi-tier storage'
    Export:
      Name: !Sub '${AWS::StackName}-RetentionPolicy'

  RecoveryMetrics:
    Description: Disaster recovery objectives achieved
    Value: 'RTO: Minutes (versioning), RPO: Real-time (S3 durability), Retention: 7 years'
    Export:
      Name: !Sub '${AWS::StackName}-RecoveryMetrics'

  CostOptimization:
    Description: Storage cost optimization features
    Value: 'Lifecycle policies + Multi-class storage + Bucket key encryption'
    Export:
      Name: !Sub '${AWS::StackName}-CostOptimization'