AWSTemplateFormatVersion: '2010-09-09'
Description: 'Patient Vital Signs Monitoring - S3 Resources for Healthcare Dashboard'

Parameters:
  ProjectName:
    Type: String
    Default: VitalSignsMonitoring
    Description: Name of the project, used as prefix for resource names

Resources:
  # S3 Bucket for hosting the healthcare dashboard
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-dashboard-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - ETag
            Id: myCORSRuleId1
            MaxAge: 3600
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: Frontend

  # Bucket policy to allow public read access for website hosting
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${WebsiteBucket.Arn}/*'

  # S3 Bucket for storing patient data exports (optional, encrypted)
  PatientDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-patient-data-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
          - Id: MoveToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: PatientData
        - Key: Encryption
          Value: AES256

Outputs:
  WebsiteBucketName:
    Description: Name of the S3 bucket hosting the healthcare dashboard
    Value: !Ref WebsiteBucket
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteBucketName'

  WebsiteBucketArn:
    Description: ARN of the website bucket
    Value: !GetAtt WebsiteBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteBucketArn'

  WebsiteURL:
    Description: URL of the healthcare dashboard
    Value: !Sub 'http://${WebsiteBucket}.s3-website-${AWS::Region}.amazonaws.com'
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteURL'

  PatientDataBucket:
    Description: Name of the encrypted patient data bucket
    Value: !Ref PatientDataBucket
    Export:
      Name: !Sub '${AWS::StackName}-PatientDataBucket'

  PatientDataBucketArn:
    Description: ARN of the patient data bucket
    Value: !GetAtt PatientDataBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-PatientDataBucketArn'