AWSTemplateFormatVersion: '2010-09-09'
Description: 'Patient Vital Signs Monitoring - WAF for API Protection'

Parameters:
  ProjectName:
    Type: String
    Default: VitalSignsMonitoring
    Description: Name of the project, used as prefix for resource names
  ApiStackName:
    Type: String
    Default: vital-signs-api
    Description: Name of the API Gateway stack

Resources:
  # WAF Web ACL for API Gateway protection
  HealthcareWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub '${ProjectName}-api-protection'
      Description: 'WAF rules to protect healthcare API from common threats'
      Scope: REGIONAL  # For API Gateway
      DefaultAction:
        Allow: {}
      Rules:
        # Rate limiting rule
        - Name: RateLimitRule
          Priority: 1
          Statement:
            RateBasedStatement:
              Limit: 1000  # Max 1000 requests per 5 minutes per IP
              AggregateKeyType: IP
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub '${ProjectName}-RateLimit'

        # AWS Managed Core Rule Set
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub '${ProjectName}-CommonRuleSet'

        # AWS Managed Known Bad Inputs Rule Set
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 3
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub '${ProjectName}-BadInputs'

        # SQL injection protection
        - Name: AWSManagedRulesSQLiRuleSet
          Priority: 4
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub '${ProjectName}-SQLiProtection'

      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub '${ProjectName}-WebACL'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: Security
        - Key: Purpose
          Value: APIProtection

  # Associate WAF with API Gateway
  WebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: 
        Fn::Sub:
          - 'arn:aws:apigateway:${AWS::Region}::/restapis/${ApiId}/stages/prod'
          - ApiId:
              Fn::ImportValue: !Sub '${ApiStackName}-ApiGatewayId'
      WebACLArn: !GetAtt HealthcareWebACL.Arn

  # CloudWatch Log Group for WAF logs
  WAFLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/wafv2/${ProjectName}-webacl'
      RetentionInDays: 30
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Component
          Value: Security

  # WAF Logging Configuration
  WAFLoggingConfig:
    Type: AWS::WAFv2::LoggingConfiguration
    Properties:
      ResourceArn: !GetAtt HealthcareWebACL.Arn
      LogDestinationConfigs:
        - !GetAtt WAFLogGroup.Arn
      RedactedFields:
        - SingleHeader:
            Name: authorization
        - SingleHeader:
            Name: cookie

Outputs:
  WebACLId:
    Description: ID of the WAF Web ACL protecting the healthcare API
    Value: !Ref HealthcareWebACL
    Export:
      Name: !Sub '${AWS::StackName}-WebACLId'

  WebACLArn:
    Description: ARN of the WAF Web ACL
    Value: !GetAtt HealthcareWebACL.Arn
    Export:
      Name: !Sub '${AWS::StackName}-WebACLArn'